language: node_js

node_js:
  - stable

before_script:
  - mkdir blog && cd blog && git clone -b vue https://github.com/fydy/bga_issue.git ./ && rm -rf .git


script:
  - npm install
  - npm run build
  
after_script:
  - git init
  - git config user.name "fydy"
  - git config user.email "edu@yuns.me"
  - git add .
  - git commit -m "Update docs"
  - git push --quiet --force https://$qa@github.com/fydy/qa.git master
